#!/usr/bin/env python3
"""Generate gold AST schema and EBNF markdown files.

Usage:
    ./scripts/generate_gold.py  # updates EBNF.md and ./schemas/fuse.ast.schema.json

This script extracts the `GRAMMAR` string from `src/parser.py` and writes it to
`EBNF.md` (fenced code block). It also copies the canonical
`fuse.ast.schema.json` file into `./schemas/fuse.ast.schema.json` so
that parsing tests and reviewers can pick up a gold copy of the schema.
"""

from __future__ import annotations

import json
from pathlib import Path

# Prefer running via the project's virtualenv Python
try:
    import os, sys
    from pathlib import Path as _Path
    _here = _Path(__file__).resolve().parents[1]
    _venv_py = _here / ".venv" / "bin" / "python"
    if _venv_py.exists():
        try:
            if _Path(sys.executable).resolve() != _venv_py.resolve():
                os.execv(str(_venv_py), [str(_venv_py)] + sys.argv)
        except Exception:
            pass
except Exception:
    pass

ROOT = Path(__file__).resolve().parents[1]
PARSER = ROOT / "src" / "parser.py"
GRAMMAR_OUT = ROOT / "docs" / "ebnf.md"
SCHEMA_SRC = ROOT / "schemas" / "fuse.ast.schema.json"
SCHEMA_DST = ROOT / "tests" / "parsing" / "golden" / "fuse.ast.schema.json"


def extract_grammar(src_text: str) -> str:
    # Find GRAMMAR = r""" ... """
    start_marker = "GRAMMAR"
    i = src_text.find(start_marker)
    if i == -1:
        raise RuntimeError("Could not find GRAMMAR in parser.py")
    # Find the first triple-quote after the GRAMMAR marker
    first = src_text.find('"""', i)
    if first == -1:
        raise RuntimeError("Could not find opening triple quotes for GRAMMAR")
    second = src_text.find('"""', first + 3)
    if second == -1:
        raise RuntimeError("Could not find closing triple quotes for GRAMMAR")
    body = src_text[first + 3 : second]
    return body.strip()


def write_ebnf(ebnf: str) -> None:
    header = "# Fuse EBNF Grammar for ONNX\n\nThis file is generated by `fuse` — do not edit by hand.\n\n"
    content = header + "```fuse\n" + ebnf.strip() + "\n```\n"

    # Append a terse example (MatMul) using the canonical `node` form so the
    # generated EBNF docs show a short example of a node declaration.
    example = '''\n## Example: terse node\n\n```fuse\nnode dense(x: f32[batch, in_dim], w: f32[in_dim, out_dim]) -> f32[batch, out_dim] {\n  MatMul(x, w)\n}\n```\n'''
    content += example

    # Also append the project's examples/golden/terse.fuse if present
    terse_path = ROOT / "examples" / "golden" / "terse.fuse"
    if terse_path.exists():
        terse_text = terse_path.read_text().strip()
        content += "\n## Example: examples/golden/terse.fuse\n\n"
        content += "```fuse\n" + terse_text + "\n```\n"

    GRAMMAR_OUT.parent.mkdir(parents=True, exist_ok=True)
    GRAMMAR_OUT.write_text(content)
    print(f"Wrote EBNF to {GRAMMAR_OUT}")


def copy_schema() -> None:
    if not SCHEMA_SRC.exists():
        raise RuntimeError(f"Schema source not found: {SCHEMA_SRC}")
    SCHEMA_DST.parent.mkdir(parents=True, exist_ok=True)
    # Pretty-print schema to destination to keep formatting stable
    data = json.loads(SCHEMA_SRC.read_text())
    SCHEMA_DST.write_text(json.dumps(data, indent=2, sort_keys=False) + "\n")
    print(f"Copied schema to {SCHEMA_DST}")


if __name__ == "__main__":
    src = PARSER.read_text()
    ebnf = extract_grammar(src)
    write_ebnf(ebnf)
    copy_schema()
    print("Done.")
