"""Install IPython startup script for Fuse.

This script is intended to be invoked during Docker image build (as root) and will
write a small, robust startup loader into the default IPython profile's startup
directory so kernels loading in the container automatically register Fuse magics.

Idempotent: it overwrites the file each run.
"""
from __future__ import annotations
import os
from pathlib import Path

# Prefer an explicit env var, otherwise default to the current user's IPython profile so
# the installer works both in Docker builds (root) and local dev environments.
STARTUP_DIR = Path(os.environ.get("IPYTHON_STARTUP_DIR") or (Path.home() / ".ipython" / "profile_default" / "startup"))
STARTUP_FILE = STARTUP_DIR / "00_fuse_magics.py"

STARTUP_CONTENT = '''# Fuse IPython kernel startup script (auto-installed)
# Loads the Fuse IPython extension to make %%fuse and other magics available.
# This file is auto-generated by jupyter/scripts/install_startup.py

try:
    # Attempt a direct import only; do not perform repository-root fallbacks here.
    from src.jupyter.magics import load_ipython_extension
    from IPython import get_ipython

    ip = get_ipython()
    if ip is not None:
        load_ipython_extension(ip)
except Exception as e:
    # Fail loudly and provide clear guidance to the user about what to do.
    import sys, traceback
    print(
        "Failed to load Fuse IPython extension at startup. The 'src' package is not importable in this kernel environment. "
        "Please install Fuse into your kernel environment (e.g., `pip install -e .`) or ensure the repository root is on PYTHONPATH.",
        file=sys.stderr,
    )
    traceback.print_exc(file=sys.stderr)
    raise
'''


def install_startup():
    STARTUP_DIR.mkdir(parents=True, exist_ok=True)
    STARTUP_FILE.write_text(STARTUP_CONTENT)
    print(f"Wrote Fuse IPython startup loader to {STARTUP_FILE}")

    # Strict validation: ensure the extension is importable in the current
    # (build/installer) Python environment. If this import fails, exit
    # non-zero so automated builds fail loudly and users get early feedback.
    try:
        from src.jupyter.magics import load_ipython_extension  # type: ignore
    except Exception as e:
        import sys, traceback
        print(
            "ERROR: Fuse IPython extension could not be imported in this environment. "
            "Install the package in the Python environment used by the kernel (e.g., `pip install -e .`).", file=sys.stderr
        )
        traceback.print_exc(file=sys.stderr)
        sys.exit(1)


if __name__ == '__main__':
    install_startup()
